; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Display]
platform = espressif32
framework = arduino
monitor_speed = 115200
board = esp32-s3-devkitc-1-n16r8v
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
lib_deps = 
	FASTLED
	wire
	bblanchon/ArduinoJson@^6.21.3
	bodmer/TFT_eSPI@^2.5.43
	bodmer/JPEGDecoder@^2.0.0 
	mathieucarbou/ESPAsyncWebServer@^3.1.2
	bodmer/TFT_eWidget
	pololu/VL53L0X@^1.3.1
	; xreef/SimpleFTPServer@^3.0.1 switch to local library to fix ESP32S3 issues
	robtillaart/ADS1X15 @ ^0.5.4
	adafruit/Adafruit BusIO @ ^1.14
	adafruit/Adafruit ADS1X15@^2.5.0
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit BMP280 Library@^2.6.8
lib_ignore = AsyncTCP_RP2040W
upload_protocol = esptool
upload_speed = 921600
build_flags =
	-Os	
    ; -D ARDUINO_USB_MODE=1
	; -D ARDUINO_USB_CDC_ON_BOOT=1
    ;-D COFFEE
	-D SPRINKLER
	;-D DESK
	;-D GLIDERPORT
    ;-D POWERMETER
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D USE_HSPI_PORT
	-D CONFIG_IDF_TARGET_ESP32S3
	-D USER_SETUP_LOADED=1
	-D ILI9488_DRIVER=1
	-D TFT_WIDTH=320
	-D TFT_HEIGHT=480
	-D TFT_MISO=13
	-D TFT_MOSI=11
	-D TFT_SCLK=12
	-D TOUCH_CS=10
	-D SD_CS=42
	-D TFT_CS=21
	-D UTF8_SUPPORT
	-D FTP_AUTH_TIME_OUT=60
	-D DEFAULT_FTP_SERVER_NETWORK_TYPE_ESP32=6
	-D DEFAULT_STORAGE_TYPE_ESP32=7

	-D TFT_DC=41
	-D TFT_RST=46
	-D Z_THRESHOLD=600
	-D LOAD_GLCD=1
	-D LOAD_FONT2=1
	-D LOAD_FONT4=1
	-D LOAD_FONT6=1
	-D LOAD_FONT7=1
	-D LOAD_FONT8=1
	-D LOAD_GFXFF=1
	-D SMOOTH_FONT=1
	-D SPI_FREQUENCY=27000000
	-D SPI_TOUCH_FREQUENCY=2500000

; monitor_dtr = 1
; monitor_rts = 0